name: CI
on: [push, pull_request]

jobs:
  

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"

      - name: Build | Trunk
        run: |
          cd launchers/wasm
          trunk build

      - name: Post Setup | Upload dist
        uses: actions/upload-artifact@v3
        with:
          path: ./launchers/wasm/dist/


  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - name: Setup | Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install --fix-missing libasound2-dev libudev-dev pkg-config

      - name: Test
        run: cargo test
